app/blogengine/blog/urls.py
from django.urls import path, include
from .views import *
from allauth.socialaccount import providers
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', posts_list, name='posts_list_url'),
    path('post/create/', PostCreate.as_view(), name='post_create_url'),
    path('post/<str:slug>/', PostDetail.as_view(), name='post_detail_url'),
    path('post/<str:slug>/update/', PostUpdate.as_view(), name='post_update_url'),
    path('post/<str:slug>/delete/', PostDelete.as_view(), name='post_delete_url'),
    path('tags/', tags_list, name='tags_list_url'),
    path('colors/', colors_list, name='color_list_url'),
    path('color/<str:slug>/', ColorDetail.as_view(), name='color_detail_url'),
    path('sizes/', sizes_list, name='size_list_url'),
    path('attributesbound/', ItemAttributes.as_view(), name='bound_create_url'),
    path('attributesbound/<str:slug>/', ItemAttributes.as_view(), name='bound_detail_url'),
    path('attributes/create/', AttrsCreate.as_view(), name='attrs_create_url'),
    path('attributes/', attributes_list, name='attributes_list_url'),
    path('attributes/<str:slug>/', AttrsDetail.as_view(), name='attrs_detail_url'),
    path('attributes/<str:slug>/update/', AttrsDetail.as_view(), name='attrs_update_url'),
    path('attributes/<str:slug>/delete/', AttrsDelete.as_view(), name='attrs_delete_url'),
    path('tag/create/', TagCreate.as_view(), name='tag_create_url'),
    path('tag/<str:slug>/', TagDetail.as_view(), name='tag_detail_url'),
    path('tag/<str:slug>/update/', TagUpdate.as_view(), name='tag_update_url'),
    path('tag/<str:slug>/delete/', TagDelete.as_view(), name='tag_delete_url'),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.account.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blogengine/blogengine/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from allauth.socialaccount import providers
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from .views import redirect_blog

urlpatterns = [
    path('', redirect_blog),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('app/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.account.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Add Django site authentication urls (for login, logout, password management)

app/blogengine/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:post_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:post_id>/', views.cart_remove, name='cart_remove'),
]

app/blogengine/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/36f6b33e42.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/card.css' %}">
  <title>
    {% block title %}
        App
    {% endblock %}
  </title>

  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: white ;" id="navbar">

    </div>
    <div class="wrap">

    <a class="navbar-brand mt-2" id="navbar_main" href="{% url 'posts_list_url' %}">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">


          <a class="navbar-brand mt-1" id="navbar_tag" href="{% url 'tags_list_url' %}">Категории</a>
        </li>
        <!-- {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="navbar-brand" id="navbar_signup" href="{% url 'account_signup' %}">Регистрация</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="navbar-brand" id="navbar_login" href="{% url 'account_login' %}">Авторизация</a>
        </li>
         {% endif %} -->
      </ul>
      <form class="form-inline my-2 my-lg-0" id="search" action="{% url 'posts_list_url' %}">
        <input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search" name='search'>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
      </form>
      {% if request.user.is_authenticated %}
      <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="navbar-brand" id="navbar_logout" href="{% url 'account_logout' %}">Выход</a>
    </li>
      {% else %}

        <a class="navbar-brand" id="navbar_login" href="{% url 'account_login' %}">Авторизация</a>

      {% endif %}

  </div>
  <div class="cart">
      {% with total_items=cart|length %}
      {% if cart|length > 0 %}

      <a href="{% url 'cart:cart_detail' %}" style="text-decoration: none; color: black;"><h5 class="mt-3 ml-1"><i class="fas fa-shopping-cart"></i>
        {{ total_items }}<br>
      </h5></a>
      {% else %}
      <h5 class="mt-3 ml-1"><i class="fas fa-shopping-cart"></i> {{ total_items }}</h5>


      {% endif %}
      {% endwith %}
  </div>
    </nav>
      </head>
      </div>
          <hr style="height:1px;border:none;color:black;background-color:#333;" id="hr"/>
      <body>
    <div class="container mt-5">
      <div class="row">
          <div class="col-6 offset-md-2">

            {% block content %}
                
            {% endblock %}

              {% if is_paginated %}

            <nav aria-label="...">
              <ul class="pagination">
                <li class="page-item {% if not prev_url %} disabled {% endif %}">
                  <a class="page-link" href="{{ prev_url }}" tabindex="-1">Предыдущая</a>
                </li>
                {% for n in page_object.paginator.page_range %}

                    {% if page_object.number == n %}

                        <li class="page-item active">
                          <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
                        </li>
                    {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                    </li>
                    {% endif %}
                {% endfor %}

                <li class="page-item {% if not next_url %} disabled {% endif %}">
                  <a class="page-link" href="{{ next_url }}" tabindex="-1">Следующая</a>
                </li>
              </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>


  {% if request.user.is_authenticated and request.user.is_staff %}
    <div class="admin-panel align-items-center">
      <a href="/admin" class="btn btn-outline-primary">Admin</a>
      {% block admin-panel %}{% endblock %}

    </div>
    {% endif %}





</body>
</html>

app/blogengine/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Shopping cart
{% endblock %}



{% block content %}
  <h1>Shopping cart</h1>
  <table class='cart'>
    <thead>
      <tr>
        <th>Image</th>
        <th>Item</th>
        <th>Update quantity</th>
        <th>Delete</th>
        <th>Quantity</th>
        <th>Price for 1 item</th>
        <th>Total price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with post=item.post %}
        <tr>
          <td>
            <a href="{{ post.get_absolute_url }}">
            <img src="{% if post.image  %}{{ post.image.url }}{% endif %}">
            </a>
          </td>
          <td>{{ post.name }}</td>
          <td>
              <form class="" action="{% url 'cart:cart_add' post.id %}" method="post">
                  {{ item.update_quanity_form.quantity }}
                  {{ item.update_quanity_form.update }}
                  <input type="submit" value="Update">
                  {% csrf_token %}
              </form>
          </td>
          <td><a href="{% url 'cart:cart_remove' post.id %}">Delete</a></td>
          <td>
              {{ item.quantity }}
          </td>
          <td class='num'>{{ item.price }}$</td>
          <td class='num'>{{ item.total_price }}$</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class='total'>
          <td>Total</td>
          <td colspan="4"></td>
          <td class='num'>{{ cart.get_total_price }}$</td>
        </tr>
    </tbody>
  </table>
  <p class='text-right'>
    <a href="{% url 'blog:posts_list' %}" class='btn btn-light'>Back to shop</a>
    <a href="#" class='btn btn-primary'>Create order</a>
  </p>
{% endblock %}